version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "06:00"
      timezone: Europe/Madrid
    groups:
      npm-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: [dependencies]
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "06:00"
      timezone: Europe/Madrid
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 5
